/*
==========================================================
01 - JOINS AND AGGREGATION
AtliQ Hardware SQL Analytics Portfolio
==========================================================

Focus:
- Fact + Dimension joins
- Aggregation
- Business-level grouping
- Multi-table joins
- Gross sales calculation
- Deduction analysis
==========================================================
*/


/*
----------------------------------------------------------
Q01 - Sales by Product Division

Business Question:
Which product divisions generate the highest sales volume?

SQL Concepts:
- INNER JOIN
- GROUP BY
- SUM()
----------------------------------------------------------
*/

SELECT
    p.division,
    SUM(s.sold_quantity) AS total_sold_quantity
FROM fact_sales_monthly AS s
JOIN dim_product AS p
    ON s.product_code = p.product_code
GROUP BY p.division
ORDER BY total_sold_quantity DESC;


/*
----------------------------------------------------------
Q02 - Sales by Region

Business Question:
How much quantity was sold in each region?

SQL Concepts:
- Fact + Dimension join
- GROUP BY
- SUM()
----------------------------------------------------------
*/

SELECT
    c.region,
    SUM(s.sold_quantity) AS total_sold_quantity
FROM fact_sales_monthly AS s
JOIN dim_customer AS c
    ON s.customer_code = c.customer_code
GROUP BY c.region
ORDER BY total_sold_quantity DESC;


/*
----------------------------------------------------------
Q03 - Top 5 Customers by Sales Quantity

Business Question:
Which five customers have the highest total sales quantity?

SQL Concepts:
- JOIN
- GROUP BY
- SUM()
- ORDER BY
- LIMIT
----------------------------------------------------------
*/

SELECT
    c.customer_code,
    c.customer,
    SUM(s.sold_quantity) AS total_sold_quantity
FROM fact_sales_monthly AS s
JOIN dim_customer AS c
    ON s.customer_code = c.customer_code
GROUP BY
    c.customer_code,
    c.customer
ORDER BY total_sold_quantity DESC
LIMIT 5;


/*
----------------------------------------------------------
Q04 - Top 10 Products by Sales Quantity

Business Question:
Which products have the highest total sales quantity?

SQL Concepts:
- GROUP BY
- SUM()
- ORDER BY
- LIMIT
----------------------------------------------------------
*/

SELECT
    s.product_code,
    SUM(s.sold_quantity) AS total_sold_quantity
FROM fact_sales_monthly AS s
GROUP BY s.product_code
ORDER BY total_sold_quantity DESC
LIMIT 10;


/*
----------------------------------------------------------
Q05 - Sales by Division and Product

Business Question:
How does sales volume vary by product within each division?

SQL Concepts:
- JOIN
- GROUP BY multiple columns
- SUM()
----------------------------------------------------------
*/

SELECT
    p.division,
    p.product,
    SUM(s.sold_quantity) AS total_sold_quantity
FROM fact_sales_monthly AS s
JOIN dim_product AS p
    ON s.product_code = p.product_code
GROUP BY
    p.division,
    p.product
ORDER BY
    p.division,
    total_sold_quantity DESC;


/*
----------------------------------------------------------
Q06 - Gross Sales Detail

Business Question:
What is the gross sales value generated by each
customer-product-date combination?

Gross Sales =
sold_quantity × gross_price_per_item

SQL Concepts:
- Multiple INNER JOINs
- Fact + Dimension analysis
- Calculated columns
- ROUND()
----------------------------------------------------------
*/

SELECT
    s.date,
    s.fiscal_year,
    s.customer_code,
    c.customer,
    c.market,
    s.product_code,
    p.product,
    p.variant,
    s.sold_quantity,
    g.gross_price AS gross_price_per_item,
    ROUND(
        s.sold_quantity * g.gross_price,
        2
    ) AS gross_price_total
FROM fact_sales_monthly AS s
JOIN dim_product AS p
    ON s.product_code = p.product_code
JOIN dim_customer AS c
    ON s.customer_code = c.customer_code
JOIN fact_gross_price AS g
    ON g.fiscal_year = s.fiscal_year
    AND g.product_code = s.product_code;


/*
----------------------------------------------------------
Q07 - Gross Sales by Market

Business Question:
What is the gross sales value generated by each market?

SQL Concepts:
- Multiple JOINs
- Aggregation
- Calculated measures
----------------------------------------------------------
*/

SELECT
    c.market,
    ROUND(
        SUM(s.sold_quantity * g.gross_price),
        2
    ) AS gross_sales
FROM fact_sales_monthly AS s
JOIN dim_customer AS c
    ON s.customer_code = c.customer_code
JOIN fact_gross_price AS g
    ON g.fiscal_year = s.fiscal_year
    AND g.product_code = s.product_code
GROUP BY c.market
ORDER BY gross_sales DESC;


/*
----------------------------------------------------------
Q08 - Customer Sales by Region

Business Question:
Which customers contribute the most sales volume within
each region?

SQL Concepts:
- Multiple joins
- GROUP BY
- Aggregation
----------------------------------------------------------
*/

SELECT
    c.region,
    c.customer_code,
    c.customer,
    SUM(s.sold_quantity) AS total_sold_quantity
FROM fact_sales_monthly AS s
JOIN dim_customer AS c
    ON s.customer_code = c.customer_code
GROUP BY
    c.region,
    c.customer_code,
    c.customer
ORDER BY
    c.region,
    total_sold_quantity DESC;


/*
----------------------------------------------------------
Q09 - Pre-Invoice Discount Detail

Business Question:
How can sales, product, gross price, and pre-invoice
deduction data be combined into a detailed sales report?

SQL Concepts:
- Multiple fact/dimension joins
- Join using fiscal year
- Calculated gross sales
----------------------------------------------------------
*/

SELECT
    s.date,
    s.product_code,
    p.product,
    p.variant,
    s.sold_quantity,
    g.gross_price AS gross_price_per_item,
    ROUND(
        s.sold_quantity * g.gross_price,
        2
    ) AS gross_price_total,
    pre.pre_invoice_discount_pct
FROM fact_sales_monthly AS s
JOIN dim_product AS p
    ON s.product_code = p.product_code
JOIN fact_gross_price AS g
    ON g.fiscal_year = get_fiscal_year(s.date)
    AND g.product_code = s.product_code
JOIN fact_pre_invoice_deductions AS pre
    ON pre.customer_code = s.customer_code
    AND pre.fiscal_year = get_fiscal_year(s.date);


/*
----------------------------------------------------------
Q10 - Top Markets by Gross Sales Within Each Region

Business Question:
What are the highest gross-sales markets within each
region for a selected fiscal year?

SQL Concepts:
- JOIN
- GROUP BY
- CTE
- Aggregation
- Regional business analysis

Note:
The ranking version of this analysis is placed in
05_advanced_analytical_sql.
----------------------------------------------------------
*/

SELECT
    c.region,
    c.market,
    ROUND(
        SUM(gs.gross_price_total) / 1000000,
        2
    ) AS gross_sales_mln
FROM gross_sales AS gs
JOIN dim_customer AS c
    ON c.customer_code = gs.customer_code
WHERE gs.fiscal_year = 2021
GROUP BY
    c.region,
    c.market
ORDER BY
    c.region,
    gross_sales_mln DESC;
